//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSoapToyota
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://agv/WebService.wsdl", ConfigurationName="WebServiceSoapToyota.IOrderManagerAsHost")]
    public interface IOrderManagerAsHost
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ConfirmOrderRows", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ConfirmOrderRowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int ConfirmOrderRows(string orderId, WebServiceSoapToyota.FinishedRow[] finishedRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ConfirmOrderRows", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ConfirmOrderRowsResponse")]
        System.Threading.Tasks.Task<int> ConfirmOrderRowsAsync(string orderId, WebServiceSoapToyota.FinishedRow[] finishedRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/CreateOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/CreateOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int CreateOrder(WebServiceSoapToyota.WebServiceOrder orderToCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/CreateOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/CreateOrderResponse")]
        System.Threading.Tasks.Task<int> CreateOrderAsync(WebServiceSoapToyota.WebServiceOrder orderToCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/PauseOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/PauseOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int PauseOrder(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/PauseOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/PauseOrderResponse")]
        System.Threading.Tasks.Task<int> PauseOrderAsync(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ResumeOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ResumeOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int ResumeOrder(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ResumeOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ResumeOrderResponse")]
        System.Threading.Tasks.Task<int> ResumeOrderAsync(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AbortOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AbortOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AbortOrder(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AbortOrder", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AbortOrderResponse")]
        System.Threading.Tasks.Task<int> AbortOrderAsync(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/RemoveGoodsFromStorage", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/RemoveGoodsFromStorageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int RemoveGoodsFromStorage(string goodsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/RemoveGoodsFromStorage", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/RemoveGoodsFromStorageResponse")]
        System.Threading.Tasks.Task<int> RemoveGoodsFromStorageAsync(string goodsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AppendOrderRows", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AppendOrderRowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AppendOrderRows(string orderId, WebServiceSoapToyota.WebServiceOrderRow[] orderRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AppendOrderRows", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AppendOrderRowsResponse")]
        System.Threading.Tasks.Task<int> AppendOrderRowsAsync(string orderId, WebServiceSoapToyota.WebServiceOrderRow[] orderRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddArticleInfo", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddArticleInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AddArticleInfo(string orderId, string articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddArticleInfo", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddArticleInfoResponse")]
        System.Threading.Tasks.Task<int> AddArticleInfoAsync(string orderId, string articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddBatchInfo", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddBatchInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AddBatchInfo(string orderId, string batchId, int batchSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddBatchInfo", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddBatchInfoResponse")]
        System.Threading.Tasks.Task<int> AddBatchInfoAsync(string orderId, string batchId, int batchSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsDimension", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsDimensionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AddGoodsDimension(string orderId, int goodsWidth, int goodsHeight, int goodsLength, int goodsWeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsDimension", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsDimensionResponse")]
        System.Threading.Tasks.Task<int> AddGoodsDimensionAsync(string orderId, int goodsWidth, int goodsHeight, int goodsLength, int goodsWeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsAmount", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsAmountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AddGoodsAmount(string orderId, int goodsAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsAmount", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsAmountResponse")]
        System.Threading.Tasks.Task<int> AddGoodsAmountAsync(string orderId, int goodsAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeOrderPrio", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeOrderPrioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int ChangeOrderPrio(string orderId, int prio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeOrderPrio", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeOrderPrioResponse")]
        System.Threading.Tasks.Task<int> ChangeOrderPrioAsync(string orderId, int prio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeGoodsCarrier", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeGoodsCarrierResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int ChangeGoodsCarrier(string orderId, int goodsCarrier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeGoodsCarrier", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ChangeGoodsCarrierResponse")]
        System.Threading.Tasks.Task<int> ChangeGoodsCarrierAsync(string orderId, int goodsCarrier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ClearStorageCell", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ClearStorageCellResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int ClearStorageCell(string storage, string storageCell);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/ClearStorageCell", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/ClearStorageCellResponse")]
        System.Threading.Tasks.Task<int> ClearStorageCellAsync(string storage, string storageCell);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsToStorage", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsToStorageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int AddGoodsToStorage(string storage, string storageCell, string goodsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsToStorage", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/AddGoodsToStorageResponse")]
        System.Threading.Tasks.Task<int> AddGoodsToStorageAsync(string storage, string storageCell, string goodsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/SetInput", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/SetInputResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceOrderRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinishedRow))]
        int SetInput(int inputNumber, int state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agv/WebService.wsdl/IOrderManagerAsHost/SetInput", ReplyAction="http://agv/WebService.wsdl/IOrderManagerAsHost/SetInputResponse")]
        System.Threading.Tasks.Task<int> SetInputAsync(int inputNumber, int state);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://agv/WebService.wsdl/encoded")]
    public partial class FinishedRow
    {
        
        private int taskIdField;
        
        private int quantityField;
        
        /// <remarks/>
        public int TaskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://agv/WebService.wsdl/encoded")]
    public partial class WebServiceOrderRow
    {
        
        private int taskIdField;
        
        private int operationTypeField;
        
        private string locationField;
        
        private int quantityField;
        
        /// <remarks/>
        public int TaskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        public int OperationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://agv/WebService.wsdl/encoded")]
    public partial class WebServiceOrder
    {
        
        private WebServiceOrderRow[] orderRowsField;
        
        private string orderIdField;
        
        private int goodsCarrierField;
        
        private string goodsIdField;
        
        private int goodsContainerIdField;
        
        private int goodsWidthField;
        
        private int goodsHeightField;
        
        private int goodsLengthField;
        
        private int goodsWeightField;
        
        private string articleIDField;
        
        private string batchIDField;
        
        private int batchSizeField;
        
        private string goodsAmountField;
        
        private int prioField;
        
        private int vehicleIdField;
        
        private string goodsCategoryField;
        
        private System.DateTime dueTimeField;
        
        /// <remarks/>
        public WebServiceOrderRow[] OrderRows
        {
            get
            {
                return this.orderRowsField;
            }
            set
            {
                this.orderRowsField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsCarrier
        {
            get
            {
                return this.goodsCarrierField;
            }
            set
            {
                this.goodsCarrierField = value;
            }
        }
        
        /// <remarks/>
        public string GoodsId
        {
            get
            {
                return this.goodsIdField;
            }
            set
            {
                this.goodsIdField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsContainerId
        {
            get
            {
                return this.goodsContainerIdField;
            }
            set
            {
                this.goodsContainerIdField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsWidth
        {
            get
            {
                return this.goodsWidthField;
            }
            set
            {
                this.goodsWidthField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsHeight
        {
            get
            {
                return this.goodsHeightField;
            }
            set
            {
                this.goodsHeightField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsLength
        {
            get
            {
                return this.goodsLengthField;
            }
            set
            {
                this.goodsLengthField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsWeight
        {
            get
            {
                return this.goodsWeightField;
            }
            set
            {
                this.goodsWeightField = value;
            }
        }
        
        /// <remarks/>
        public string ArticleID
        {
            get
            {
                return this.articleIDField;
            }
            set
            {
                this.articleIDField = value;
            }
        }
        
        /// <remarks/>
        public string BatchID
        {
            get
            {
                return this.batchIDField;
            }
            set
            {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public int BatchSize
        {
            get
            {
                return this.batchSizeField;
            }
            set
            {
                this.batchSizeField = value;
            }
        }
        
        /// <remarks/>
        public string GoodsAmount
        {
            get
            {
                return this.goodsAmountField;
            }
            set
            {
                this.goodsAmountField = value;
            }
        }
        
        /// <remarks/>
        public int Prio
        {
            get
            {
                return this.prioField;
            }
            set
            {
                this.prioField = value;
            }
        }
        
        /// <remarks/>
        public int VehicleId
        {
            get
            {
                return this.vehicleIdField;
            }
            set
            {
                this.vehicleIdField = value;
            }
        }
        
        /// <remarks/>
        public string GoodsCategory
        {
            get
            {
                return this.goodsCategoryField;
            }
            set
            {
                this.goodsCategoryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DueTime
        {
            get
            {
                return this.dueTimeField;
            }
            set
            {
                this.dueTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IOrderManagerAsHostChannel : WebServiceSoapToyota.IOrderManagerAsHost, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OrderManagerAsHostClient : System.ServiceModel.ClientBase<WebServiceSoapToyota.IOrderManagerAsHost>, WebServiceSoapToyota.IOrderManagerAsHost
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderManagerAsHostClient() : 
                base(OrderManagerAsHostClient.GetDefaultBinding(), OrderManagerAsHostClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOrderManagerAsHost.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderManagerAsHostClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderManagerAsHostClient.GetBindingForEndpoint(endpointConfiguration), OrderManagerAsHostClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderManagerAsHostClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderManagerAsHostClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderManagerAsHostClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderManagerAsHostClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderManagerAsHostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int ConfirmOrderRows(string orderId, WebServiceSoapToyota.FinishedRow[] finishedRows)
        {
            return base.Channel.ConfirmOrderRows(orderId, finishedRows);
        }
        
        public System.Threading.Tasks.Task<int> ConfirmOrderRowsAsync(string orderId, WebServiceSoapToyota.FinishedRow[] finishedRows)
        {
            return base.Channel.ConfirmOrderRowsAsync(orderId, finishedRows);
        }
        
        public int CreateOrder(WebServiceSoapToyota.WebServiceOrder orderToCreate)
        {
            return base.Channel.CreateOrder(orderToCreate);
        }
        
        public System.Threading.Tasks.Task<int> CreateOrderAsync(WebServiceSoapToyota.WebServiceOrder orderToCreate)
        {
            return base.Channel.CreateOrderAsync(orderToCreate);
        }
        
        public int PauseOrder(string orderId)
        {
            return base.Channel.PauseOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<int> PauseOrderAsync(string orderId)
        {
            return base.Channel.PauseOrderAsync(orderId);
        }
        
        public int ResumeOrder(string orderId)
        {
            return base.Channel.ResumeOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<int> ResumeOrderAsync(string orderId)
        {
            return base.Channel.ResumeOrderAsync(orderId);
        }
        
        public int AbortOrder(string orderId)
        {
            return base.Channel.AbortOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<int> AbortOrderAsync(string orderId)
        {
            return base.Channel.AbortOrderAsync(orderId);
        }
        
        public int RemoveGoodsFromStorage(string goodsId)
        {
            return base.Channel.RemoveGoodsFromStorage(goodsId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveGoodsFromStorageAsync(string goodsId)
        {
            return base.Channel.RemoveGoodsFromStorageAsync(goodsId);
        }
        
        public int AppendOrderRows(string orderId, WebServiceSoapToyota.WebServiceOrderRow[] orderRows)
        {
            return base.Channel.AppendOrderRows(orderId, orderRows);
        }
        
        public System.Threading.Tasks.Task<int> AppendOrderRowsAsync(string orderId, WebServiceSoapToyota.WebServiceOrderRow[] orderRows)
        {
            return base.Channel.AppendOrderRowsAsync(orderId, orderRows);
        }
        
        public int AddArticleInfo(string orderId, string articleId)
        {
            return base.Channel.AddArticleInfo(orderId, articleId);
        }
        
        public System.Threading.Tasks.Task<int> AddArticleInfoAsync(string orderId, string articleId)
        {
            return base.Channel.AddArticleInfoAsync(orderId, articleId);
        }
        
        public int AddBatchInfo(string orderId, string batchId, int batchSize)
        {
            return base.Channel.AddBatchInfo(orderId, batchId, batchSize);
        }
        
        public System.Threading.Tasks.Task<int> AddBatchInfoAsync(string orderId, string batchId, int batchSize)
        {
            return base.Channel.AddBatchInfoAsync(orderId, batchId, batchSize);
        }
        
        public int AddGoodsDimension(string orderId, int goodsWidth, int goodsHeight, int goodsLength, int goodsWeight)
        {
            return base.Channel.AddGoodsDimension(orderId, goodsWidth, goodsHeight, goodsLength, goodsWeight);
        }
        
        public System.Threading.Tasks.Task<int> AddGoodsDimensionAsync(string orderId, int goodsWidth, int goodsHeight, int goodsLength, int goodsWeight)
        {
            return base.Channel.AddGoodsDimensionAsync(orderId, goodsWidth, goodsHeight, goodsLength, goodsWeight);
        }
        
        public int AddGoodsAmount(string orderId, int goodsAmount)
        {
            return base.Channel.AddGoodsAmount(orderId, goodsAmount);
        }
        
        public System.Threading.Tasks.Task<int> AddGoodsAmountAsync(string orderId, int goodsAmount)
        {
            return base.Channel.AddGoodsAmountAsync(orderId, goodsAmount);
        }
        
        public int ChangeOrderPrio(string orderId, int prio)
        {
            return base.Channel.ChangeOrderPrio(orderId, prio);
        }
        
        public System.Threading.Tasks.Task<int> ChangeOrderPrioAsync(string orderId, int prio)
        {
            return base.Channel.ChangeOrderPrioAsync(orderId, prio);
        }
        
        public int ChangeGoodsCarrier(string orderId, int goodsCarrier)
        {
            return base.Channel.ChangeGoodsCarrier(orderId, goodsCarrier);
        }
        
        public System.Threading.Tasks.Task<int> ChangeGoodsCarrierAsync(string orderId, int goodsCarrier)
        {
            return base.Channel.ChangeGoodsCarrierAsync(orderId, goodsCarrier);
        }
        
        public int ClearStorageCell(string storage, string storageCell)
        {
            return base.Channel.ClearStorageCell(storage, storageCell);
        }
        
        public System.Threading.Tasks.Task<int> ClearStorageCellAsync(string storage, string storageCell)
        {
            return base.Channel.ClearStorageCellAsync(storage, storageCell);
        }
        
        public int AddGoodsToStorage(string storage, string storageCell, string goodsId)
        {
            return base.Channel.AddGoodsToStorage(storage, storageCell, goodsId);
        }
        
        public System.Threading.Tasks.Task<int> AddGoodsToStorageAsync(string storage, string storageCell, string goodsId)
        {
            return base.Channel.AddGoodsToStorageAsync(storage, storageCell, goodsId);
        }
        
        public int SetInput(int inputNumber, int state)
        {
            return base.Channel.SetInput(inputNumber, state);
        }
        
        public System.Threading.Tasks.Task<int> SetInputAsync(int inputNumber, int state)
        {
            return base.Channel.SetInputAsync(inputNumber, state);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrderManagerAsHost))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrderManagerAsHost))
            {
                return new System.ServiceModel.EndpointAddress("http://0.0.0.0:8080/OrderManagerHost");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrderManagerAsHostClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOrderManagerAsHost);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrderManagerAsHostClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOrderManagerAsHost);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOrderManagerAsHost,
        }
    }
}
