//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSoapAgilog
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceOrderRow", Namespace="http://tempuri.org/")]
    public partial class WebServiceOrderRow : object
    {
        
        private int TaskIdField;
        
        private int OperationTypeField;
        
        private string LocationField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TaskId
        {
            get
            {
                return this.TaskIdField;
            }
            set
            {
                this.TaskIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int OperationType
        {
            get
            {
                return this.OperationTypeField;
            }
            set
            {
                this.OperationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceSoapAgilog.IOperations")]
    public interface IOperations
    {
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento orderId dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/TransportOrderStatusUpdate", ReplyAction="*")]
        WebServiceSoapAgilog.TransportOrderStatusUpdateResponse TransportOrderStatusUpdate(WebServiceSoapAgilog.TransportOrderStatusUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/TransportOrderStatusUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceSoapAgilog.TransportOrderStatusUpdateResponse> TransportOrderStatusUpdateAsync(WebServiceSoapAgilog.TransportOrderStatusUpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransportOrderStatusUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransportOrderStatusUpdate", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceSoapAgilog.TransportOrderStatusUpdateRequestBody Body;
        
        public TransportOrderStatusUpdateRequest()
        {
        }
        
        public TransportOrderStatusUpdateRequest(WebServiceSoapAgilog.TransportOrderStatusUpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportOrderStatusUpdateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int statusId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebServiceSoapAgilog.WebServiceOrderRow[] orderRows;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int palletType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string udcCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int palletWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int palletHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int palletLenght;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int palletWeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int vehicleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int errorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int palletAmount;
        
        public TransportOrderStatusUpdateRequestBody()
        {
        }
        
        public TransportOrderStatusUpdateRequestBody(string orderId, int statusId, WebServiceSoapAgilog.WebServiceOrderRow[] orderRows, int palletType, string udcCode, int palletWidth, int palletHeight, int palletLenght, int palletWeight, int vehicleId, int errorCode, int palletAmount)
        {
            this.orderId = orderId;
            this.statusId = statusId;
            this.orderRows = orderRows;
            this.palletType = palletType;
            this.udcCode = udcCode;
            this.palletWidth = palletWidth;
            this.palletHeight = palletHeight;
            this.palletLenght = palletLenght;
            this.palletWeight = palletWeight;
            this.vehicleId = vehicleId;
            this.errorCode = errorCode;
            this.palletAmount = palletAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransportOrderStatusUpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransportOrderStatusUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceSoapAgilog.TransportOrderStatusUpdateResponseBody Body;
        
        public TransportOrderStatusUpdateResponse()
        {
        }
        
        public TransportOrderStatusUpdateResponse(WebServiceSoapAgilog.TransportOrderStatusUpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportOrderStatusUpdateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TransportOrderStatusUpdateResult;
        
        public TransportOrderStatusUpdateResponseBody()
        {
        }
        
        public TransportOrderStatusUpdateResponseBody(int TransportOrderStatusUpdateResult)
        {
            this.TransportOrderStatusUpdateResult = TransportOrderStatusUpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IOperationsChannel : WebServiceSoapAgilog.IOperations, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OperationsClient : System.ServiceModel.ClientBase<WebServiceSoapAgilog.IOperations>, WebServiceSoapAgilog.IOperations
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OperationsClient() : 
                base(OperationsClient.GetDefaultBinding(), OperationsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(EndpointConfiguration endpointConfiguration) : 
                base(OperationsClient.GetBindingForEndpoint(endpointConfiguration), OperationsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OperationsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OperationsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceSoapAgilog.TransportOrderStatusUpdateResponse WebServiceSoapAgilog.IOperations.TransportOrderStatusUpdate(WebServiceSoapAgilog.TransportOrderStatusUpdateRequest request)
        {
            return base.Channel.TransportOrderStatusUpdate(request);
        }
        
        public int TransportOrderStatusUpdate(string orderId, int statusId, WebServiceSoapAgilog.WebServiceOrderRow[] orderRows, int palletType, string udcCode, int palletWidth, int palletHeight, int palletLenght, int palletWeight, int vehicleId, int errorCode, int palletAmount)
        {
            WebServiceSoapAgilog.TransportOrderStatusUpdateRequest inValue = new WebServiceSoapAgilog.TransportOrderStatusUpdateRequest();
            inValue.Body = new WebServiceSoapAgilog.TransportOrderStatusUpdateRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.statusId = statusId;
            inValue.Body.orderRows = orderRows;
            inValue.Body.palletType = palletType;
            inValue.Body.udcCode = udcCode;
            inValue.Body.palletWidth = palletWidth;
            inValue.Body.palletHeight = palletHeight;
            inValue.Body.palletLenght = palletLenght;
            inValue.Body.palletWeight = palletWeight;
            inValue.Body.vehicleId = vehicleId;
            inValue.Body.errorCode = errorCode;
            inValue.Body.palletAmount = palletAmount;
            WebServiceSoapAgilog.TransportOrderStatusUpdateResponse retVal = ((WebServiceSoapAgilog.IOperations)(this)).TransportOrderStatusUpdate(inValue);
            return retVal.Body.TransportOrderStatusUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceSoapAgilog.TransportOrderStatusUpdateResponse> WebServiceSoapAgilog.IOperations.TransportOrderStatusUpdateAsync(WebServiceSoapAgilog.TransportOrderStatusUpdateRequest request)
        {
            return base.Channel.TransportOrderStatusUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceSoapAgilog.TransportOrderStatusUpdateResponse> TransportOrderStatusUpdateAsync(string orderId, int statusId, WebServiceSoapAgilog.WebServiceOrderRow[] orderRows, int palletType, string udcCode, int palletWidth, int palletHeight, int palletLenght, int palletWeight, int vehicleId, int errorCode, int palletAmount)
        {
            WebServiceSoapAgilog.TransportOrderStatusUpdateRequest inValue = new WebServiceSoapAgilog.TransportOrderStatusUpdateRequest();
            inValue.Body = new WebServiceSoapAgilog.TransportOrderStatusUpdateRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.statusId = statusId;
            inValue.Body.orderRows = orderRows;
            inValue.Body.palletType = palletType;
            inValue.Body.udcCode = udcCode;
            inValue.Body.palletWidth = palletWidth;
            inValue.Body.palletHeight = palletHeight;
            inValue.Body.palletLenght = palletLenght;
            inValue.Body.palletWeight = palletWeight;
            inValue.Body.vehicleId = vehicleId;
            inValue.Body.errorCode = errorCode;
            inValue.Body.palletAmount = palletAmount;
            return ((WebServiceSoapAgilog.IOperations)(this)).TransportOrderStatusUpdateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8081/DataStoreService.svc");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OperationsClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OperationsClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding,
        }
    }
}
