name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.202' # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['7.0.X' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        id: stepid
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Create temporary global.json
        run: echo '{"sdk":{"version":"${{ steps.stepid.outputs.dotnet-version }}"}}'./global.json
      - name: Execute dotnet
        run: dotnet build <C:\Users\UTSPC-08\Documents\GitHub\CI_Test\TestCICD\TestCICD-csproj>