name: Test Actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
	Test Lorenzo codice Yaml:
    		runs-on: ubuntu-latest
    
   	 	push:
     		 branches:
        		- main

    		steps:
			- run: 
			- name: Checkout
        			uses: actions/checkout@v3
				with: 
					fetch-depth: 0
			-run: |
				for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              			git checkout $commit
              			echo "run test"
          			done
			

