name: CI

on:
  push:
    branches:
      - main

env:
  Greetings: Gianluzzz



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Show files changed
         run: cat $C:\Users\UTSPC-08\Documents\GitHub\CI_Test
       - 


